<Project Sdk="Microsoft.NET.Sdk.Razor">
	<PropertyGroup>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<AddRazorSupportForMvc>true</AddRazorSupportForMvc>
		<StaticWebAssetBasePath>/</StaticWebAssetBasePath>
	</PropertyGroup>


	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ContentTargetFolders>.</ContentTargetFolders>
		<Product>UmbracoForm.MailChimp.WorkFlow</Product>
		<PackageId>UmbracoForm.MailChimp.WorkFlow</PackageId>
		<Title>UmbracoForm.MailChimp.WorkFlow</Title>
		<Description>Umbraco Forms V17 Mailchimp Integration WorkflowType</Description>
		<Product>...</Product>
		<PackageTags>NET10 Umbraco-CMS Umbraco-Forms Mailchimp Subscriber-to-Mailchimp-list,umbraco-form-workflow Mailchimp umbraco-marketplace</PackageTags>
		<RootNamespace>UmbracoForm.MailChimp.WorkFlow</RootNamespace>
		<Version>17.0.0.0</Version>
		<Authors>Harikrushna Parmar | uThemes</Authors>
		<Company>uThemes - madnat Technologies</Company>
		<Copyright>$([System.DateTime]::UtcNow.ToString(`yyyy`)) © uThemes - Madnat Technologies</Copyright>
		<RepositoryType>Git</RepositoryType>
		<PackageProjectUrl>https://github.com/harikrishna43/UmbracoForms.Mailchimp.WorkFlow</PackageProjectUrl>
		<RepositoryUrl>https://github.com/harikrishna43/UmbracoForms.Mailchimp.WorkFlow</RepositoryUrl>
		<PackageIcon>mailchimpICO.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageReleaseNotes>Updated package compatible with Umbraco Forms v17 </PackageReleaseNotes>
		<PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
	</PropertyGroup>

	<ItemGroup>
		<None Include="README.md" Pack="true" PackagePath=""/>
		<None Include="mailchimpICO.png" Pack="true" PackagePath=""/>
	</ItemGroup>
	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="MailChimp.Net.V3" Version="5.8.2" />
		<PackageReference Include="Umbraco.Cms.Web.Website" Version="*" />
		<PackageReference Include="Umbraco.Cms.Web.Common" Version="*" />
		<PackageReference Include="Umbraco.Cms.Api.Common" Version="*" />
		<PackageReference Include="Umbraco.Cms.Api.Management" Version="*" />
		<PackageReference Include="Umbraco.Forms.Core" Version="17.0.3" />
	</ItemGroup>

	<ItemGroup>
		<!-- Dont include the client folder as part of packaging nuget build -->
		<Content Remove="Client\**" />

		<!-- However make the Umbraco-package.json included for dotnet pack or nuget package and visible to the solution -->
		<None Include="Client\public\umbraco-package.json" Pack="false" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="wwwroot\" />
	</ItemGroup>

</Project>
	